{% set name = "dogpile.cache" %}
{% set version = "0.7.1" %}
{% set sha256 = "691b7f199561c4bd6e7e96f164a43cc3781b0c87bea29b7d59d859f873fd4a31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1000
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python
    - pip
    - six
  run:
    - python
    - six

test:
  imports:
    - dogpile.cache

about:
  home: https://bitbucket.org/zzzeek/dogpile.cache
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A caching front-end based on the Dogpile lock.

extra:
  recipe-maintainers:
    - brainstorm
