{% set name = "dogpile.cache" %}
{% set version = "0.6.7" %}
{% set sha256 = "fca7deb7c276b879b01c15c5d39b3c05701dc43b263ec3fef1e52cb851cf88ab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - dogpile.cache 

about:
  home: https://bitbucket.org/zzzeek/dogpile.cache
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A caching front-end based on the Dogpile lock. 

extra:
  recipe-maintainers:
    - brainstorm
