{% set name = "dogpile.cache" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dogpile.cache-{{ version }}.tar.gz
  sha256: 6f0bcf97c73bfec1a7bf14e5a248488cee00c2d494bf63f3789ea6d95a57c1cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - decorator >=4.0.0
    - python >=3.6
    - stevedore >=3.0.0

test:
  imports:
    - dogpile
    - dogpile.cache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sqlalchemy/dogpile.cache
  summary: A caching front-end based on the Dogpile lock.
  doc_url: https://pythonhosted.org/dogpile.cache/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - brainstorm
