travis:
  secure:
    BINSTAR_TOKEN: ogqEyMFYlLW52La5kDJ00S5kBFJ0S8vfCl3fTBIWIzy0TIhDfXLFyviPfG6g4t0O66OuqxqOJciulY2NxWopha4a2vsd/KcCt1ETtX4i4Ptcjc7/dG2DOO7zLuo3/z9KQNRhc5b8KLSfKz6ME1hlkJfDBn6rcNHmANrcreEQhzM35jrE8XA7Qtu/v170d0ui6Wixt4OZdkBkHyqwDwhkRD1D0Zp/R9/DCsED/fPv2ENSxHDACwwP8bMgNlAblwOZklQ3Vw6bLq78w3J3yxhQ11Mnx3uizv0I/4I5mn+xhErkvNU7/53R16sPYya3rcnOSBKcpRHvUNS+6fj2p/yZmgffNqGNqNijvpCKT+PDyLs8yvXbecsnlsr3kw0dvpJZ3hOcNih5ue9iIkvnAOIeQi91fclgHZmEOi4PiW4ubxa+fucXR8b1YpHY8Df0EcwF/ErBShUhruuTjn/HDTQ2s+iaszhB6qA8AmhkMBbak8w7SKJd9NWIua9W3yfNa8whVGoFSnQY468vWOAYOV68UElts8Fp9N3Vj9Zv8KDzCxKN3YEOdqJa096WuBdYQMHvyz2jb7hz0LJ1fzdwp40u0JF8+LWoSQOO/72CpnQdPiiglfbTvph1gAm27cEaKLo+I8BwVVxLswtFxB/SKQXqEJ1ipaEvI/4HLCMjXkFiMeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
