travis:
  secure:
    BINSTAR_TOKEN: U5nzU/aIM4/SqFS3jtdsIw5AzT/ZzzTkoQMlOJNZ4zawoYsoABfE2AoEjjYM9fzOEzQt3xEo65rUlJgoI5PBlHyQswas/ibxHZUieZW14yTnveFfbylTJPJ9IZct50iBRHgRcfroRlagL3mEM7z+4rSiX1k6WLzC3lSBGQ+C+7u/FxtP83F+riYWYkiG6uWj7G9xVGtx0R46r9sO1BvFeTQrkjTw7JsHFUsn9wlygkYTa3gFdXOo5GVZqNm4p6j1xTMQhPWJMc522tztBvHSQPlEdz+nHg9mps77sUd1auvZQ/aeeK59p0QcGn2xTuQR8yunghCsoewdnArXEz7EcIcG6Alqr5+gNfeDcookR6R7plP757O2OeEU4eAUWsMQlf6XvDk0l9t71mUtkUsAM7RWbzchwKX+QPV+waOC+c5TueDqbZ0AR0yNesmXxmZf9Riyi2LEERRzSyuaV1FQAmoNlNCyI5M2fbZ1pWgsRiXbxJfd4DhbSOKLBFGSg2fsqUI1r7VD5dy+yp/uxkVrZkxq43ZAMtRfEMzZMTz2+EqB+UnuFlcmRxg/6Xgg0JTj/h44vcY/pBnYkE/UfZ0OJUR7iZYLbbepVVouEABdgVw9Ft/4HVmClg1oA49wRcH31AHE/06rZ8mfSIgojPLx1BPoVOlv6Txv5Z2i/QNhmEs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
