travis:
  secure:
    BINSTAR_TOKEN: dV0lS8xA0g1Q1nst9BbI6yMR960C1yZxWXTaFDmk1VKF6ng3MpSc2MDJtASHKV7J15dAkinfhSt+t1YywePmvW0Q6cGrl7C71eeq/0Et6zXVHSZqM4EztFz2Zgl5sGFJEyr0J6a3fZgRilztHYItGLPwq9XqNahZ8Do5r2CRtHy902v2PQQTAeZRuDjg1ZhZW7kyXuSCVPnBdZUFB35JvRDwbtDHo/QkDLQ33ros6PjG5E+3zKCAB5ISTrxVJOot+Q2pRWD/ctpuBN338HnbXzbUxbzzkWu3cuAvOF5u57zo04GDcdx+nItYjwwDQvao1UYTE1yFQBEB8j1UAtRM1H72etRp11ZJrP+3UBOQMWWn5H1IXPY+lMFTXxLo11EMNlvhLv4LVdVy1mDCRKRjtHhAdnPyD4K+FcbdP9eQLcfM2CFDY/JfeORI3XnpoMPZUzlnIKNnW7YpwC7M9iD6hiR89WDz2t0Tau2ux8/mrpONR/D/gAllSoPYL7OWEuiz9dWLiH208wtX/+/LFjiSpNweyqysu9196UBFFG1+T8JNpDduFurdolFz8J1dioW7Tmjw9g3G7enU0aig/2kTU5YROPLMpFMGvpRMxxYErXv21+t7fau0pZMIGlyzdKzaf8Jg5XbCe8BPDPyu61DcuYzrxOWP0XuJErJBNodfCNc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
